# Generated by Django 4.1.7 on 2023-05-16 14:25

from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('masv', models.TextField(primary_key=True, serialize=False)),
                ('hoten', models.TextField(max_length=100)),
                ('ngaysinh', models.DateField(validators=[myapp.models.validate_date])),
                ('quequan', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'sinhvien',
            },
        ),
    ]
